[project]
name = "makemore"
description = "â™»ï¸ Generate more of the same stuff"
authors = [
    { name = "Luca Baggi", email = "57922983+baggiponte@users.noreply.github.com" },
]
dynamic = []
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "torch>=2.0.1",
    "numpy>=1.22.0",
    "requests>=2.27.0",
    "typing-extensions>=4.7.1 ; python_version < '3.11'",
]
version = "0.1.8"

[tool.pdm.dev-dependencies]
precommit = [
    "pre-commit>=2.20.0",
    "black>=23.3.0",
    "blacken-docs>=1.14.0",
    "deptry>=0.12.0",
    "mypy>=1.3.0",
    "pip-audit>=2.5.6",
    "ruff>=0.0.272",
    "types-requests>=2.27.0",
]
docs = [
    "mkdocs>=1.4.2",
    "mkdocs-material>=9.0.2",
    "mkdocstrings[python]>=0.20.0",
    "mike>=1.1.2",
    "setuptools>=67.5.1",
]
test = [
    "pytest>=7.2.0",
    "pytest-cov>=4.0.0",
]
release = [
    "commitizen>=2.42.0",
]
ide = [
    "jupyterlab>=4.0.5",
    "nbstripout>=0.6.1",
    "matplotlib>=3.7.2",
]

[tool.pdm.version]
source = "file"
path = "src/makemore/__init__.py"

[tool.pdm.build]
excludes = [
    "**/.DS_Store",
]
package-dir = "src"
source-includes = [
    "tests",
    "CHANGELOG.md",
    "README.md",
]

[tool.ruff]
src = [
    "src",
]
target-version = "py39"
line-length = 88
select = [
    "E",
    "F",
    "A",
    "B",
    "BLE",
    "C4",
    "D",
    "DTZ",
    "FBT",
    "G",
    "I",
    "N",
    "RET",
    "S",
    "TRY",
    "UP",
    "W",
    "YTT",
]
fix = true
ignore = [
    "D107",
    "E501",
    "TRY003",
]

[tool.ruff.per-file-ignores]
"__init__.py" = [
    "F401",
    "I002",
]

[tool.ruff.pydocstyle]
convention = "google"

[tool.ruff.pycodestyle]
max-doc-length = 88

[tool.ruff.isort]
required-imports = [
    "from __future__ import annotations",
]

[tool.commitizen]
name = "cz_conventional_commits"
version = "0.1.8"
version_files = [
    "src/makemore/__init__.py:^__version__",
]
annotated_tag = true
incremental = true
update_changelog_on_bump = true

[tool.commitizen.change_type_map]
feat = "âš¡ Feat"
fix = "ðŸž Fix"
perf = "ðŸš€ Performance"
refactor = "ðŸ›   Refactor"
docs = "ðŸ“š Docs"

[tool.mypy]
python_version = "3.9"
python_executable = ".venv/bin/python"
show_error_codes = true
check_untyped_defs = true
disallow_any_unimported = true
disallow_untyped_defs = true
no_implicit_optional = true
warn_return_any = true
warn_unused_ignores = true

[tool.pytest.ini_options]
testpaths = "tests"
pythonpath = "src"

[tool.deptry.per_rule_ignores]
DEP002 = [
    "numpy",
]

[tool.pyright]
exclude = [
    ".venv",
]
venvPath = "."
venv = ".venv"

[build-system]
requires = [
    "pdm-pep517>=1.0",
]
build-backend = "pdm.pep517.api"
