[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "ch340_nrf"
version = "0.0.3"
authors = [{ name = "drakeerv", email = "drakeerv@outlook.com" }]
description = "Allows you to use the ch340 nrf usb adapter with python. This project is currently in developement."
readme = "README.md"
requires-python = ">=3.0"
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
]
dependencies = ["pyserial"]

[project.urls]
"Homepage" = "https://github.com/drakeerv/ch340_nrf"
"Bug Tracker" = "https://github.com/drakeerv/ch340_nrf/issues"
