# YAML configuration file for atmega48-88-168-328 variants
#
# Copyright 2021 Clement Savergne <csavergne@yahoo.com>
#
# This file is part of yasim-avr.
#
# yasim-avr is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# yasim-avr is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with yasim-avr.  If not, see <http://www.gnu.org/licenses/>.

---
#========================================================================================
PORT:
    registers:
        - name: PUD
          address: 0x35
          fields:
            PUD: { kind: BIT, pos: 4 }

        - name: PORT
          offset: 0x02

        - name: DDR
          offset: 0x01

        - name: PIN
          offset: 0x00

#========================================================================================
EXTINT:
    registers:
        - name: EICRA
          address: 0x49
          fields:
            ISC0:
                kind: ENUM
                LSB: 0
                MSB: 1
                values: [ LOW, TOGGLE, FALLING, RISING ]
            ISC1:
                kind: ENUM
                LSB: 2
                MSB: 3
                values: [ LOW, TOGGLE, FALLING, RISING ]

        - name: EIMSK
          address: 0x1D
          fields:
            INT0: { kind: BIT, pos: 0, one: enabled, zero: disabled }
            INT1: { kind: BIT, pos: 1, one: enabled, zero: disabled }

        - name: EIFR
          address: 0x1C
          fields:
            INTF0: { kind: BIT, pos: 0 }
            INTF1: { kind: BIT, pos: 1 }

        - name: PCICR
          address: 0x48
          fields:
            PCIE0: { kind: BIT, pos: 0, one: enabled, zero: disabled }
            PCIE1: { kind: BIT, pos: 1, one: enabled, zero: disabled }
            PCIE2: { kind: BIT, pos: 2, one: enabled, zero: disabled }

        - name: PCIFR
          address: 0x1B
          fields:
            PCIF0: { kind: BIT, pos: 0, one: enabled, zero: disabled }
            PCIF1: { kind: BIT, pos: 1, one: enabled, zero: disabled }
            PCIF2: { kind: BIT, pos: 2, one: enabled, zero: disabled }

        - name: PCMSK0
          address: 0x4B
          fields:
            PCINT0: { kind: BIT, pos: 0, one: enabled, zero: disabled }
            PCINT1: { kind: BIT, pos: 1, one: enabled, zero: disabled }
            PCINT2: { kind: BIT, pos: 2, one: enabled, zero: disabled }
            PCINT3: { kind: BIT, pos: 3, one: enabled, zero: disabled }
            PCINT4: { kind: BIT, pos: 4, one: enabled, zero: disabled }
            PCINT5: { kind: BIT, pos: 5, one: enabled, zero: disabled }
            PCINT6: { kind: BIT, pos: 6, one: enabled, zero: disabled }
            PCINT7: { kind: BIT, pos: 7, one: enabled, zero: disabled }

        - name: PCMSK1
          address: 0x4C
          fields:
            PCINT8: { kind: BIT, pos: 0, one: enabled, zero: disabled }
            PCINT9: { kind: BIT, pos: 1, one: enabled, zero: disabled }
            PCINT10: { kind: BIT, pos: 2, one: enabled, zero: disabled }
            PCINT11: { kind: BIT, pos: 3, one: enabled, zero: disabled }
            PCINT12: { kind: BIT, pos: 4, one: enabled, zero: disabled }
            PCINT13: { kind: BIT, pos: 5, one: enabled, zero: disabled }
            PCINT14: { kind: BIT, pos: 6, one: enabled, zero: disabled }

        - name: PCMSK2
          address: 0x4D
          fields:
            PCINT16: { kind: BIT, pos: 0, one: enabled, zero: disabled }
            PCINT17: { kind: BIT, pos: 1, one: enabled, zero: disabled }
            PCINT18: { kind: BIT, pos: 2, one: enabled, zero: disabled }
            PCINT19: { kind: BIT, pos: 3, one: enabled, zero: disabled }
            PCINT20: { kind: BIT, pos: 4, one: enabled, zero: disabled }
            PCINT21: { kind: BIT, pos: 5, one: enabled, zero: disabled }
            PCINT22: { kind: BIT, pos: 6, one: enabled, zero: disabled }
            PCINT23: { kind: BIT, pos: 7, one: enabled, zero: disabled }

    config:
        extint_pins: [ PD2, PD3 ]
        pcint_pins: [ PB0, PB1, PB2, PB3, PB4, PB5, PB6, PB7,
                      PC0, PC1, PC2, PC3, PC4, PC5, PC6, "",
                      PD0, PD1, PD2, PD3, PD4, PD5, PD6, PD7 ]
        rb_extint_ctrl : [ EICRA, "ISC0 | ISC1" ]
        rb_extint_mask : [ EIMSK, "INT0 | INT1" ]
        rb_extint_flag : [ EIFR, "INTF0 | INTF1" ]
        rb_pcint_ctrl : PCICR
        rb_pcint_flag : PCIFR
        reg_pcint_mask : [ PCMSK0, PCMSK1, PCMSK2 ]
        extint_vector : [ INT0, INT1 ]
        pcint_vector : [ PCINT0, PCINT1, PCINT2 ]

#========================================================================================
USART:
    registers:
        - name: UDR
          address: 0xA6

        - name: UCSRA
          address: 0xA0
          fields:
            MPCM: { kind: BIT, pos: 0 }
            U2X: { kind: BIT, pos: 1 }
            UPE: { kind: BIT, pos: 2 }
            DOR: { kind: BIT, pos: 3, readonly: yes }
            FE: { kind: BIT, pos: 4, readonly: yes }
            UDRE: { kind: BIT, pos: 5, readonly: yes }
            TXC: { kind: BIT, pos: 6 }
            RXC: { kind: BIT, pos: 7, readonly: yes }

        - name: UCSRB
          address: 0xA1
          fields:
            TXB8: { kind: BIT, pos: 0 }
            RXB8: { kind: BIT, pos: 1, readonly: yes }
            UCSZ2: { kind: BIT, pos: 2 }
            TXEN: { kind: BIT, pos: 3 }
            RXEN: { kind: BIT, pos: 4 }
            UDRIE: { kind: BIT, pos: 5 }
            TXCIE: { kind: BIT, pos: 6 }
            RXCIE: { kind: BIT, pos: 7 }

        - name: UCSRC
          address: 0xA2
          fields:
            UCPOL: { kind: BIT, pos: 0 }
            UCSZ:
                kind:  ENUM
                LSB: 1
                MSB: 2

            USBS: { kind: BIT, pos: 3, one: "1-bit", zero: "2-bits" }

            UPM:
                kind:  ENUM
                LSB: 4
                MSB: 5
                values: [ Disabled, "", Even, Odd ]

            UMSEL:
                kind:  ENUM
                LSB: 6
                MSB: 7
                values: [ Async, Sync, "", Master SPI ]

        - name: UBRR
          address: 0xA4
          size: 2
          fields:
            BAUD:
                kind: INT
                LSB: 0
                MSB: 11

    config:
        reg_data : UDR
        rb_rx_enable: [ UCSRB, RXEN ]
        rb_tx_enable: [ UCSRB, TXEN ]
        rb_rxc_inten: [ UCSRB, RXCIE ]
        rb_rxc_flag: [ UCSRA, RXC ]
        rb_txc_inten: [ UCSRB, TXCIE ]
        rb_txc_flag: [ UCSRA, TXC ]
        rb_txe_inten: [ UCSRB, UDRIE ]
        rb_txe_flag: [ UCSRA, UDRE ]
        rb_baud_2x: [ UCSRA, U2X ]
        reg_baud: UBRR
        baud_bitsize: 12
        rxc_vector: USART_RX
        txc_vector: USART_TX
        txe_vector: USART_UDRE

#========================================================================================
SPI:
    registers:
        - name: CTRLA
          offset: 0x00
          fields:
            ENABLE: { kind: BIT, pos: 0, one: enabled, zero: disabled }
            PRESC:
                kind: ENUM
                LSB: 1
                MSB: 2
                values: [ DIV4, DIV16, DIV64, DIV128 ]
            CLK2X: { kind: BIT, pos: 4, one: 2X, zero: 1X }
            MASTER: { kind: BIT, pos: 5, one: master, zero: slave }
            DORD: { kind: BIT, pos: 6, one: "LSB first", zero: "MSB first" }

        - name: CTRLB
          offset: 0x01
          fields:
            MODE:
                kind: ENUM
                LSB: 0
                MSB: 1
                values: [ MODE0, MODE1, MODE2, MODE3 ]

            SSD: { kind: BIT, pos: 2, one: disable, zero: enable }
            BUFWR: { kind: BIT, pos: 6 }
            BUFEN: { kind: BIT, pos: 7 }

        - name: INTCTRL
          offset: 0x02
          fields:
            IE: { kind: BIT, pos: 0 }
            SSIE: { kind: BIT, pos: 4 }
            DREIE: { kind: BIT, pos: 5 }
            TXCIE: { kind: BIT, pos: 6 }
            RXCIE: { kind: BIT, pos: 7 }

        - name: INTFLAGS
          offset: 0x03
          fields:
            WRCOL: { kind: BIT, pos: 6 }
            IF: { kind: BIT, pos: 7 }

            BUFOVF: { kind: BIT, pos: 0 }
            SSIF: { kind: BIT, pos: 4 }
            DREIF: { kind: BIT, pos: 5 }
            TXCIF: { kind: BIT, pos: 6 }
            RXCIF: { kind: BIT, pos: 7 }

        - name: DATA
          offset: 0x04

#========================================================================================
TWI:
    registers:
        - name: CTRLA
          offset: 0x00
          fields:
            FMPEN: { kind: BIT, pos: 1, one: enabled, zero: disabled }
            SDAHOLD:
                kind: ENUM
                LSB: 2
                MSB: 3
                values: [ OFF, 50ns, 300ns, 500ns ]
            SDASETUP: { kind: BIT, pos: 4, one: 8CYC, zero: 4CYC }

        - name: DUALCTRL
          offset: 0x01
          fields:
            ENABLE: { kind: BIT, pos: 0 , one: enabled, zero: disabled }
            FMPEN: { kind: BIT, pos: 1, one: enabled, zero: disabled }
            SDAHOLD:
                kind: ENUM
                LSB: 2
                MSB: 3
                values: [ OFF, 50ns, 300ns, 500ns ]

        - name: DBGCTRL
          offset: 0x02
          supported: no

        - name: MCTRLA
          offset: 0x03
          fields:
            ENABLE: { kind: BIT, pos: 0, one: enabled, zero: disabled }
            SMEN: { kind: BIT, pos: 1, one: enabled, zero: disabled }
            TIMEOUT:
                kind: ENUM
                LSB: 2
                MSB: 3
                values: [ disabled, 50us, 100us, 200us ]
            QCEN: { kind: BIT, pos: 4, one: enabled, zero: disabled }
            WIEN: { kind: BIT, pos: 6, one: enabled, zero: disabled }
            RIEN: { kind: BIT, pos: 7, one: enabled, zero: disabled }

        - name: MCTRLB
          offset: 0x04
          fields:
            MCMD:
                kind: ENUM
                LSB: 0
                MSB: 1
                values: [ NOACT, REPSTART, RECVTRANS, STOP ]
            ACKACT: { kind: BIT, pos: 2, one: nack, zero: ack }
            FLUSH: { kind: BIT, pos: 3 }

        - name: MSTATUS
          offset: 0x05
          fields:
            BUSSTATE:
                kind: ENUM
                LSB: 0
                MSB: 1
                values: [ UNKNOWN, IDLE, OWNER, BUSY ]
            BUSERR: { kind: BIT, pos: 2, one: error, zero: ok }
            ARBLOST: { kind: BIT, pos: 3 }
            RXACK: { kind: BIT, pos: 4, readonly: yes, one: nack, zero: ack }
            CLKHOLD: { kind: BIT, pos: 5 }
            WIF: { kind: BIT, pos: 6 }
            RIF: { kind: BIT, pos: 7 }

        - name: MBAUD
          offset: 0x06
          fields:
            BAUD:
                kind: INT

        - name: MADDR
          offset: 0x07
          fields:
            ADDR:
                kind: RAW

        - name: MDATA
          offset: 0x08
          fields:
            DATA:
                kind: RAW

        - name: SCTRLA
          offset: 0x09
          fields:
            ENABLE: { kind: BIT, pos: 0, one: enabled, zero: disabled }
            SMEN: { kind: BIT, pos: 1, one: enabled, zero: disabled }
            PMEN: { kind: BIT, pos: 2, one: enabled, zero: disabled }
            PIEN: { kind: BIT, pos: 4, one: enabled, zero: disabled }
            APIEN: { kind: BIT, pos: 6, one: enabled, zero: disabled }
            DIEN: { kind: BIT, pos: 7, one: enabled, zero: disabled }

        - name: SCTRLB
          offset: 0x0A
          fields:
            SCMD:
                kind: ENUM
                LSB: 0
                MSB: 1
                values: { 0:NOACT, 2:COMPTRANS, 3:RESPONSE }
            ACKACT: { kind: BIT, pos: 2, one: nack, zero: ack }

        - name: SSTATUS
          offset: 0x0B
          fields:
            AP: { kind: BIT, pos: 0, readonly: yes, one: adr, zero: stop }
            DIR: { kind: BIT, pos: 1, readonly: yes, one: "m<-s", zero: "m->s" }
            BUSERR: { kind: BIT, pos: 2, one: error, zero: ok }
            COLL: { kind: BIT, pos: 3 }
            RXACK: { kind: BIT, pos: 4, readonly: yes, one: nack, zero: ack }
            CLKHOLD: { kind: BIT, pos: 5 }
            APIF: { kind: BIT, pos: 6 }
            DIF: { kind: BIT, pos: 7 }

        - name: SADDR
          offset: 0x0C
          fields:
            ADDR:
                kind: RAW

        - name: SDATA
          offset: 0x0D
          fields:
            DATA:
                kind: RAW

        - name: SADDRMASK
          offset: 0x0E
          fields:
            ADDREN: { kind: BIT, pos: 0, one: enabled, zero: disabled }
            ADDRMASK:
                kind: RAW
                LSB: 1
                MSB: 7

#========================================================================================
