# This file should be in the future instead of setup.py
# https://python-poetry.org/docs/pyproject

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.poetry]
name = "database-infrastructure-local"
# I believe we are still using the version from setup.py and not from here until potery will work
version = "0.0.7" # https://pypi.org/project/operational-hours-local-python-package
description = "database-infrastructure-local-python-package Python Package"
readme = "README.md"
authors = [
    "Circlez.ai <info@circlez.ai>",
]
