[project]
name = "airless"
version = "0.0.45"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project.urls]
"Homepage" = "https://github.com/astercapital/airless"
"Bug Tracker" = "https://github.com/astercapital/airless/issues"