# SPDX-License-Identifier: MIT

[tool.ruff]
target-version = "py38"
line-length = 120
ignore = ["F403", "F405"]

[tool.ruff.per-file-ignores]
"mcsrvstat/__init__.py" = ["F401"]

[tool.black]
target-version = ["py38"]
line-length = 120
skip-string-normalization = true