

[tool.poetry]
name = "clear-skies-slack"
version = "0.9.0"
description = "clearskies bindings for Slack"
authors = [
    "Conor Mancone <cmancone@gmail.com>",
]
repository = "https://github.com/cmancone/clearskies-slack"
license = "MIT"
readme = "./README.md"
packages = [
    { include = "clearskies_slack", from = "src" }
]

[tool.poetry.dependencies]
python = "^3.8"
clear-skies = "^1.14.4"

[[tool.poetry.source]]
name = "PyPI"
priority = "primary"

[tool.poetry.group.dev.dependencies]
pre-commit = "^3.2.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
