[build-system]
requires = ["setuptools>=61.0", "discord.py>=2.3"]
build-backend = "setuptools.build_meta"

[project]
name = "AidenLib"
version = "0.1.5"
authors = [
  { name="Aiden Pearce" },
]
description = "AidenLib is a library for Aiden's projects."
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/Ken-Miles/aidenlib"
"Bug Tracker" = "https://github.com/Ken-Miles/aidenlib/issues"