[project]
name = "BitBridge"
description = "A modern Python interface to the Bitcoin Core RPC, offering both synchronous and asynchronous support."
authors = [
    {name = "godd0t", email = "lirrishala@gmail.com"},
]
dependencies = [
    "httpx>=0.24.1",
    "rich>=13.5.2",
]
requires-python = ">=3.10"
readme = "README.md"
license = {text = "MIT"}
dynamic = ["version"]

[project.optional-dependencies]
test = [
    "pytest>=7.4.1",
    "pytest-asyncio>=0.21.1",
    "pytest-sugar>=0.9.7",
    "coverage[toml]>=7.3.0",
    "faker>=19.3.1",
]
lint = [
    "ruff>=0.0.287",
    "black>=23.7.0",
]
[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.version]
path = "bitbridge/__init__.py"

[tool.hatch.build]
sources = ["bitbridge"]

[tool.hatch.build.targets.wheel]
sources = ["bitbridge"]


[tool.ruff]
cache-dir = "~/.cache/ruff"
src = ["bitbridge"]
format = "text"
line-length = 88
extend-exclude = [
    "migrations",
    "test_data",
]
target-version = "py311"
ignore = ["E501"]
ignore-init-module-imports = true

# Formatting
[tool.black]
line-length = 88
target-version = ["py311"]
include = '\.pyi?$'

# Testing
[tool.pytest.ini_options]
minversion = "7.4.1"
addopts = "-ra -q --force-sugar --log-cli-level=INFO"
testpaths = ["tests"]
pythonpath = ["bitbridge", "."]
asyncio_mode = "auto"
python_files = "tests.py test_*.py *_tests.py"
